name: chem
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.5=py312h98912ed_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.12=h4ab18f5_0
  - aom=3.9.1=hac33072_0
  - apptools=5.1.0=pyh44b312d_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - biopython=1.84=py312h9a8786e_0
  - blosc=1.21.6=hef167b5_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2024.7.4=pyhd8ed1ab_0
  - chardet=5.2.0=py312h7900ff3_1
  - configobj=5.0.8=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - eigen=3.4.0=h00ab1b0_0
  - envisage=6.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=7.0.1=gpl_h3589c0a_102
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h41a817b_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py312h98912ed_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.0.3=py312h30efb56_0
  - gst-plugins-base=1.24.5=hbaaba92_0
  - gstreamer=1.24.5=haf2f30d_0
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - jsoncpp=1.9.5=h4bd325d_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=23_linux64_openblas
  - libboost=1.84.0=hba137d9_3
  - libboost-python=1.84.0=py312hf74af30_4
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=23_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp18.1=18.1.8=default_hf981a13_1
  - libclang13=18.1.8=default_h9def88c_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.9.0=hdb1bdb2_0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=14.1.0=h77fa898_0
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.0=ha6d2627_1004
  - libgomp=14.1.0=h77fa898_0
  - libgpg-error=1.50=h4f305b6_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=23_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.8=h8b73ec9_1
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopenvino=2024.2.0=h2da1b83_1
  - libopenvino-auto-batch-plugin=2024.2.0=hb045406_1
  - libopenvino-auto-plugin=2024.2.0=hb045406_1
  - libopenvino-hetero-plugin=2024.2.0=h5c03a75_1
  - libopenvino-intel-cpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-gpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-npu-plugin=2024.2.0=he02047a_1
  - libopenvino-ir-frontend=2024.2.0=h5c03a75_1
  - libopenvino-onnx-frontend=2024.2.0=h07e8aee_1
  - libopenvino-paddle-frontend=2024.2.0=h07e8aee_1
  - libopenvino-pytorch-frontend=2024.2.0=he02047a_1
  - libopenvino-tensorflow-frontend=2024.2.0=h39126c6_1
  - libopenvino-tensorflow-lite-frontend=2024.2.0=he02047a_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - librdkit=2024.03.5=h79cfef2_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libsystemd0=255=h3516f8a_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=hb711507_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=h4ab18f5_1
  - loguru=0.7.2=py312h7900ff3_1
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib-base=3.9.1=py312h9201f00_0
  - mayavi=4.8.2=pyqt_py312h6f1e363_305
  - mpg123=1.32.6=h59595ed_0
  - msgpack-python=1.0.8=py312h2492b07_0
  - multidict=6.0.5=py312h98912ed_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - nlohmann_json=3.11.3=h59595ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.102=h593d115_0
  - numpy=2.0.1=py312h1103770_0
  - ocl-icd=2.3.2=hd590300_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4bc722e_2
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.4.0=py312h287a98d_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - ply=3.11=pyhd8ed1ab_2
  - proj=9.4.1=hb784bbd_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pycairo=1.26.1=py312h3bc4990_0
  - pyface=8.0.0=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - python=3.12.4=h194c7f8_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=ha2b5568_22
  - qt6-main=6.7.2=h0f8cd61_2
  - rdkit=2024.03.5=py312h7b4b7d0_1
  - readline=8.2=h8228510_1
  - reportlab=4.2.2=py312h9a8786e_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scipy=1.14.0=py312hc2bc53b_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=71.0.4=pyhd8ed1ab_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sqlalchemy=2.0.31=py312h9a8786e_0
  - sqlite=3.46.0=h6d4b2fc_0
  - statsmodels=0.14.2=py312h085067d_0
  - svt-av1=2.1.0=hac33072_0
  - tbb=2021.12.0=h434a139_3
  - tbb-devel=2021.12.0=hfcbfbdb_3
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - traits=6.4.3=py312h98912ed_0
  - traitsui=8.0.0=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - utfcpp=4.0.5=ha770c72_0
  - vtk=9.3.1=qt_py312hadc0db7_202
  - vtk-base=9.3.1=qt_py312hb690231_202
  - vtk-io-ffmpeg=9.3.1=qt_py312he1e5eab_202
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wslink=2.1.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.4=h4ab18f5_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yarl=1.9.4=py312h98912ed_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/rmontalvao/miniforge3/envs/chem
